### ISSUE TITLE
error on creation of availabilities

### ISSUE THREAD

**Issue by konne** [florianeck/redmine_auto_deputy#2] opened 2016-05-17 06:55 UTC
Input 2016-05-17 into From -> From

https://support.qlik2go.net/user_deputies/set_availabilities

```
TypeError (wrong argument type Date (expected String)):
  plugins/easyproject/easy_plugins/easy_extensions/lib/easy_patch/core/string.rb:7:in `downcase'
  plugins/easyproject/easy_plugins/easy_extensions/lib/easy_patch/core/string.rb:7:in `compare'
  plugins/easyproject/easy_plugins/easy_extensions/lib/easy_patch/core/string.rb:24:in `<=>'
  plugins/redmine_auto_deputy/lib/redmine_auto_deputy/user_availability_extension.rb:28:in `<'
  plugins/redmine_auto_deputy/lib/redmine_auto_deputy/user_availability_extension.rb:28:in `validate_unavailabilities'
  plugins/redmine_auto_deputy/app/controllers/user_deputies_controller.rb:46:in `set_availabilities'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by florianeck** [comment] 2016-05-17 09:15
from the first look that seems like testing with this bug happening is currently impossible, @konne can you confirm that, if yes i'd look at/fix that immedatly

**Comment by konne** [comment] 2016-05-17 09:19
yes I can confirm that bug, and don't get any availabilities into the inpurt fiels

**Comment by florianeck** [comment] 2016-05-17 10:46
@konne i cant reproduce that locally... can you provide the log output including the part where the actual post request is made?

it should start with sth. like `Started POST "/user_deputies/set_availabilities"`

**Comment by konne** [comment] 2016-05-17 11:33
now it is working, I have no idea why

**Comment by florianeck** [comment] 2016-05-17 12:13
ok, weird. i'll close this issue though, if it happens again, please copy the log with the request data included.

**Closed by florianeck** 2016-05-17 12:13 UTC
